name: aws_s3_client_updated
description: Client library to interact with the AWS S3 API with updated dependencies
version: 0.2.0
publish_to: 'none'
homepage: https://github.com/idrats/aws_s3_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  crypto: ^3.0.0
  http_client: ^1.5.1
  xml: ^6.1.0
  http: ^0.13.5
  path: ^1.8.2
  mime: ^1.0.0

dev_dependencies:
  test: ^1.0.0
